### ISSUE TITLE
Invalid package name in package.json

### ISSUE THREAD

**Issue by hyyan** [Collaborne/paper-collapse-item#33]
The element defines the package name as `@collaborne/paper-collapse-item` in `package.json` but the element is published without the `@collaborne` namespace on NPM

**Comment by ankon** [comment]
Good one!

This was introduced with https://github.com/Collaborne/paper-collapse-item/pull/31, I'll look into it.

**Comment by ankon** [comment]
@michaelscript, would you mind to allow us to take over the name `paper-collapse-item` in npm so we can publish this component to there? It seems you published this component there (probably because of the borked name... :D), so things should stay stable.

(https://www.npmjs.com/package/paper-collapse-item)

**Comment by MichaelScript** [comment]
@ankon Yup! For sure! You can email me mgreen at rosey.io I believe I just need your npm username to do the transfer.

**Comment by MichaelScript** [comment]
Fixed

**Comment by ankon** [comment]
Thank you very much! I've started working on bringing the build back into shape, so there will be a release soon.
